apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  externalIPs:
  - 10.10.10.10
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: http
  selector:
    app: grafana
  sessionAffinity: None
  type: ClusterIP
